## YAML Template.
---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Tesis
    username: root
    password: 
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
